import styles from './_svgs.module.scss';

export const EmptyGalleryIllustration = () => (
  <svg className={styles.svg} viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg">
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="0.5"
      y="0.5"
      width="399"
      height="299"
      rx="14.5"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="20.5"
      y="67.5"
      width="99"
      height="129"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="37.5"
      y="84.5"
      width="65"
      height="95"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="150.5"
      y="0.5"
      width="55"
      height="33"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="160.5"
      y="0.5"
      width="35"
      height="23"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="228.5"
      y="8.5"
      width="69"
      height="87"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="239.5"
      y="19.5"
      width="47"
      height="65"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="362.5"
      y="93.5"
      width="37"
      height="63"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="374.5"
      y="105.5"
      width="25"
      height="39"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="0.5"
      y="0.5"
      width="399"
      height="299"
      rx="14.5"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="20.5"
      y="67.5"
      width="99"
      height="129"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="37.5"
      y="84.5"
      width="65"
      height="95"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="150.5"
      y="0.5"
      width="55"
      height="33"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="160.5"
      y="0.5"
      width="35"
      height="23"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="228.5"
      y="8.5"
      width="69"
      height="87"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="239.5"
      y="19.5"
      width="47"
      height="65"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="362.5"
      y="93.5"
      width="37"
      height="63"
    />
    <rect
      className={styles.stroke}
      vectorEffect="non-scaling-stroke"
      x="374.5"
      y="105.5"
      width="25"
      height="39"
    />
  </svg>
);
